shrubs <- read.csv("shrub-volume-experiment.csv")
names(shrubs)
str(shrubs)
head(shrubs)
select(shrubs, length)
print(head(shrubs))
print(select(shrubs, length))
select(shrubs, site, experiment)
print(select(shrubs, site, experiment))
filter(shrubs, height > 5)
print(filter(shrubs, height > 5))
shrub_data_w_vols <- mutate(shrubs, "volume" = length*width*height)
print(shrub_data_w_vols)